import { adapterFactory as baseAdapterFactory } from 'calendar-utils/date-adapters/date-fns';
import {
  getISOWeek,
  getDate,
  getYear,
  getMonth,
  getWeek,
  getDay,
  getHours,
  getMinutes,
  getSeconds,
  addSeconds,
  addMinutes,
  addDays,
  addWeeks,
  addMonths,
  addYears,
  subSeconds,
  subMinutes,
  subHours,
  subDays,
  subWeeks,
  subMonths,
  subYears,
  setDate,
  setMonth,
  setYear,
  max,
  min,
  format,
  isBefore,
  isAfter,
  isSameDay
} from 'date-fns';
import { DateAdapter } from '../date-adapter';

export function adapterFactory(): DateAdapter {
  return {
    ...baseAdapterFactory(),
    getISOWeek,
    getDate,
    getYear,
    getMonth,
    getWeek,
    getDay,
    getHours,
    getMinutes,
    getSeconds,
    addSeconds,
    addMinutes,
    addDays,
    addWeeks,
    addMonths,
    addYears,
    subSeconds,
    subMinutes,
    subHours,
    subDays,
    subWeeks,
    subMonths,
    subYears,
    setDate,
    setMonth,
    setYear,
    max,
    min,
    format,
    isBefore,
    isAfter,
    isSameDay
  };
}
